### ISSUE TITLE
Problem baking badge

### ISSUE THREAD

**Issue by MrsPeppermint** [csev/obi-sample#4]
ERROR MESSAGE: 

Fatal error: Uncaught Error: Call to undefined function mcrypt_encrypt() in /homepages/17/d88943663/htdocs/obi-sample/index.php:16 Stack trace: #0 {main} thrown in /homepages/17/d88943663/htdocs/obi-sample/index.php on line 16

Line 16 in index.php calls a function that "has been DEPRECATED as of PHP 7.1.0 and REMOVED as of PHP 7.2.0. Relying on this function is highly discouraged." (Source: https://www.php.net/manual/en/function.mcrypt-encrypt.php)

**Comment by csev** [comment]
This has now been fixed - you you please re-test and check.   And by the way - I upgraded the badges to OBI 2.0 as a side effect of this issue - so thanks.
